- name: Add application user 
  ansible.builtin.user:
    name: roboshop

- name: Removing directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Createing directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download application code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes 
